# Simulation config
TICK_LENGTH_IN_SECONDS = 1
AVERAGE_CALL_FREQUENCY = 5

# Building config
NUM_FLOORS = 15
NUM_ELEVATORS = 1
FLOOR_HEIGHT = 4.0

# Agent config
EPSILON = 0.05
STEP_SIZE = 0.1
DISCOUNT_RATE = 0.99

# Elevator config
MAX_VELOCITY=3.0
ACCELERATION=1.0
FLOOR_TIME=2
STOP_TIME=7
TURN_TIME=1